In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from numpy import mean

In [3]:
#Input Dataset
dataset = pd.read_csv('hasilpreproces_labeled.csv', delimiter = ';', quoting = 3)
corpus = dataset['text'].tolist()
# corpus = ['suka tidak bisa sesuai tingkat bawa rasa',
#           'tidak usah alas guna tidak tahu sopan santun',
#           'suka sama sini tampar',
#          ]

In [4]:
#TF IDF
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

In [5]:
#Cross Val NB
classifierNB = BernoulliNB()
cv_nb = cross_val_score(classifierNB, x, y, cv = 10)
print(cv_nb)
print("Rata - Rata Akurasi : ",mean(cv_nb))

[0.65974026 0.68051948 0.67230169 0.67620286 0.68790637 0.68530559
 0.69960988 0.6189857  0.56827048 0.49674902]
Rata - Rata Akurasi :  0.6445591339739585


In [6]:
#Cross Val Adaboost NB 
classifierBoost = AdaBoostClassifier(base_estimator = BernoulliNB())
cv_ada = cross_val_score(classifierBoost, x, y, cv = 10)
print(cv_ada)
print("Rata - Rata Akurasi : ",mean(cv_ada))

[0.35324675 0.35324675 0.35370611 0.35240572 0.35240572 0.35240572
 0.35240572 0.35240572 0.35370611 0.35370611]
Rata - Rata Akurasi :  0.3529640450576732


In [7]:
#Split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1)

In [8]:
#Test Klasifikasi NB
classifierNB.fit(x_train, y_train)
preds = classifierNB.predict(x_test)

#Klasifikasi Data NB
classifierNB.fit(x_train, y_train)
data_pred = classifierNB.predict(x)

In [9]:
#Confusion Matrix Test NB
cm_nb = confusion_matrix(y_test, preds)
print('Confusion Matrix Data Test Naive Bayes :\n\n', cm_nb,'\n')

print('========================================')
print('========================================\n')

#Confusion Matrix Data NB
cm_Dnb = confusion_matrix(y, data_pred)
print('Confusion Matrix Data Real Naive Bayes :\n\n', cm_Dnb)

Confusion Matrix Data Test Naive Bayes :

 [[181   6  91]
 [  8  31  77]
 [ 29  17 330]] 


Confusion Matrix Data Real Naive Bayes :

 [[2268   22  425]
 [  49  610  620]
 [  85   25 3588]]


In [10]:
#Nilai Test Confusion Matrix NB
score_nb = classification_report(y_test, preds, zero_division=0)
print('Score Confusion Matrix Data Test Naive Bayes :\n\n', score_nb)

print('========================================================')
print('========================================================\n')

#Nilai Data Confusion Matrix NB
score_Dnb = classification_report(y, data_pred, zero_division=0)
print('Score Confusion Matrix Data Real Naive Bayes :\n\n', score_Dnb)

Score Confusion Matrix Data Test Naive Bayes :

               precision    recall  f1-score   support

          -1       0.83      0.65      0.73       278
           0       0.57      0.27      0.36       116
           1       0.66      0.88      0.76       376

    accuracy                           0.70       770
   macro avg       0.69      0.60      0.62       770
weighted avg       0.71      0.70      0.69       770


Score Confusion Matrix Data Real Naive Bayes :

               precision    recall  f1-score   support

          -1       0.94      0.84      0.89      2715
           0       0.93      0.48      0.63      1279
           1       0.77      0.97      0.86      3698

    accuracy                           0.84      7692
   macro avg       0.88      0.76      0.79      7692
weighted avg       0.86      0.84      0.83      7692



In [11]:
#Klasifikasi Test Adaboost NB
classifierBoost.fit(x_train, y_train)
pred_boost = classifierBoost.predict(x_test)

#Klasifikasi Data Adaboost NB
classifierBoost.fit(x_train, y_train)
Dpred_boost = classifierBoost.predict(x)

In [12]:
#Confusion Matrix Test Adaboost NB
cm_ad = confusion_matrix(y_test, pred_boost)
print('Confusion Matrix Data Test AdaBoost Naive Bayes :\n\n', cm_ad,'\n')

print('========================================')
print('========================================\n')

#Confusion Matrix Test Adaboost NB
cm_Dad = confusion_matrix(y, Dpred_boost)
print('Confusion Matrix Data Real Adaboost Naive Bayes :\n\n', cm_Dad)

Confusion Matrix Data Test AdaBoost Naive Bayes :

 [[278   0   0]
 [116   0   0]
 [376   0   0]] 


Confusion Matrix Data Real Adaboost Naive Bayes :

 [[2715    0    0]
 [1279    0    0]
 [3698    0    0]]


In [13]:
#Nilai Test Confusion Matrix Adaboost NB
score_ad = classification_report(y_test,pred_boost, zero_division=0)
print('Score Confusion Matrix Data Test Adaboost Naive Bayes :\n\n', score_ad)

print('========================================================')
print('========================================================\n')

#Nilai Data Confusion Matrix Adaboost NB
score_Dad =classification_report(y,Dpred_boost, zero_division=0)
print('Score Confusion Matrix Data Real Adaboost Naive Bayes :\n\n', score_Dad)

Score Confusion Matrix Data Test Adaboost Naive Bayes :

               precision    recall  f1-score   support

          -1       0.36      1.00      0.53       278
           0       0.00      0.00      0.00       116
           1       0.00      0.00      0.00       376

    accuracy                           0.36       770
   macro avg       0.12      0.33      0.18       770
weighted avg       0.13      0.36      0.19       770


Score Confusion Matrix Data Real Adaboost Naive Bayes :

               precision    recall  f1-score   support

          -1       0.35      1.00      0.52      2715
           0       0.00      0.00      0.00      1279
           1       0.00      0.00      0.00      3698

    accuracy                           0.35      7692
   macro avg       0.12      0.33      0.17      7692
weighted avg       0.12      0.35      0.18      7692

